export const theme = {
  color: {
    surface: "#f8f9fa",
    surfaceContainerLowest: "#ffffff",
    surfaceContainerLow: "#f3f4f5",
    surfaceContainer: "#edeeef",
    surfaceContainerHigh: "#e7e8e9",
    surfaceContainerHighest: "#e1e3e4",
    onSurface: "#191c1d",
    onSurfaceStrong: "#090a0b",
    onSurfaceVariant: "#464555",
    outline: "#777587",
    outlineVariant: "#c7c4d8",
    primary: "#3525cd",
    primaryContainer: "#4f46e5",
    primaryFixed: "#e2dfff",
    primaryFixedDim: "#c3c0ff",
    primaryAccent: "#2400d8",
    secondaryFixed: "#dae2fd",
    error: "#ba1a1a",
    errorContainer: "#ffdad6",
    success: "#0b7a2a",
    successContainer: "#dff8e7",
    warningContainer: "#ffdeda",
  },
} as const;

export const colorClasses = {
  appBackground: "bg-[#f8f9fa]",
  surface: "bg-white",
  surfaceLow: "bg-[#f3f4f5]",
  surfaceSubtle: "bg-[#e5e7e9]",
  text: "text-[#191c1d]",
  textStrong: "text-[#090a0b]",
  textMuted: "text-[#464555]",
  textSubtle: "text-[#777587]",
  primaryText: "text-[#3525cd]",
  primaryAccentText: "text-[#2400d8]",
  errorText: "text-[#ba1a1a]",
  primaryBg: "bg-[#3525cd]",
  primaryHoverBg: "hover:bg-[#4f46e5]",
  primarySoftBg: "bg-[#e2dfff]",
  border: "border-[#c7c4d8]",
  focusBorder: "focus:border-[#3525cd]",
  hoverText: "hover:text-[#3525cd]",
  hoverBorder: "hover:border-[#3525cd]",
} as const;

export const badgeColorClasses = {
  neutral: "bg-[#e5e7e9] text-[#303041]",
  muted: "bg-[#e5e7e9] text-[#464555]",
  primary: "bg-[#c9c0ff] text-[#2400d8]",
  info: "bg-[#dfe6ff] text-[#303041]",
  success: "bg-[#dff8e7] text-[#0b7a2a]",
  warning: "bg-[#ffdeda] text-[#ba1a1a]",
  error: "bg-[#ffe0dc] text-[#ba1a1a]",
} as const;
