import {
  FiBarChart2,
  FiCreditCard,
  FiEdit3,
  FiFileText,
  FiFolder,
  FiGrid,
  FiLayers,
  FiPenTool,
  FiSettings,
  FiTrendingUp,
  FiUser,
} from "react-icons/fi";
import { RouteTypes } from "@/types/routesTypes";

export const AdminRoutes: RouteTypes[] = [
  {
    menuHeading: "Menu",
    routeName: "/dashboard",
    menuName: "Dashboard",
    subMenuNames: [],
    requiredRoles: ["USER", "ADMIN"],
    icon: <FiGrid size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/portfolios",
    menuName: "Portfolios",
    subMenuNames: [],
    requiredRoles: ["USER", "ADMIN"],
    icon: <FiFolder size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/user-management",
    menuName: "User Management",
    subMenuNames: [],
    requiredRoles: ["ADMIN"],
    icon: <FiUser size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/resume-builder",
    menuName: "Resumes",
    subMenuNames: [],
    requiredRoles: ["USER", "ADMIN"],
    icon: <FiFileText size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/templates",
    menuName: "Templates",
    subMenuNames: [],
    requiredRoles: ["USER", "ADMIN"],
    icon: <FiLayers size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/resume-builder",
    menuName: "AI Writer",
    subMenuNames: [],
    requiredRoles: ["USER"],
    icon: <FiEdit3 size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/category",
    menuName: "Categories",
    subMenuNames: [],
    requiredRoles: ["ADMIN"],
    icon: <FiGrid size={20} />,
  },
  {
    menuHeading: "Platform",
    routeName: "/ats-analyzer",
    menuName: "ATS Analyzer",
    subMenuNames: [],
    requiredRoles: ["USER", "ADMIN"],
    icon: <FiBarChart2 size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/dashboard",
    menuName: "Portfolio Optimizer",
    subMenuNames: [],
    requiredRoles: ["USER", "ADMIN"],
    icon: <FiTrendingUp size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/dashboard",
    menuName: "Theme Assistant",
    subMenuNames: [],
    requiredRoles: ["USER"],
    icon: <FiPenTool size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/dashboard",
    menuName: "Analytics",
    subMenuNames: [],
    requiredRoles: ["USER", "ADMIN"],
    icon: <FiBarChart2 size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/settings",
    menuName: "Billing",
    subMenuNames: [],
    requiredRoles: ["ADMIN"],
    icon: <FiCreditCard size={20} />,
  },
  {
    menuHeading: "",
    routeName: "/settings",
    menuName: "Settings",
    subMenuNames: [],
    requiredRoles: ["USER", "ADMIN"],
    icon: <FiSettings size={20} />,
  },
];
